### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by pirony** [posva/vue-plugin-template#10]
I get this error in myplugin.common.js when I try to use myplugin in another app... I think it's an issue with mix module.exports and export, but I can't find a fix
Any idea?
Keep up the good work! ;)

**Comment by pirony** [comment]
I have a bit more infos...
The error is thrown only when the plugin is used with Nuxt, in every other cases it works well.

**Comment by posva** [comment]
what was happening at the end?

**Comment by pirony** [comment]
I was loading the plugin from outside node_modules for testing purpose, as soon as I put it in node_modules, it worked like a charm

**Comment by posva** [comment]
ok, thanks for reporting back
