### ISSUE TITLE
Using vue-i18n for the components

### ISSUE THREAD

**Issue by wushan** [posva/vue-plugin-template#11]
I am new to writing my own plugin, I tried this awesome template and build some `Hello World` components, push to private npm registry for my other projects. It just works !

Now I want extract some part of my existing project ( nuxt ) as a reusable plugin, I ran into an i18n issue, how do I use the vue-i18n (`$t('some.translates')`) features in this template, which makes we can set a default locale prop to ensure the rendered language is correct ? 

is that possible ?

What I am expecting 
`<my-component :local="en", :source="demoSource"></my-component>`

Template
`<h1>{{$t('string.translated')}}</h1>`

en.json
`string: { translated: 'Hello World.' }`

**Comment by posva** [comment]
Well, you can distribute your components and say you need to have a `$t` method declared in your Vue prototype or that they require vue-18n.
But usually, a reusable component receives all the information it displays from the outside as props, so you shouldn't be facing that problem
