### ISSUE TITLE
How to import component style ? 

### ISSUE THREAD

**Issue by onekiloparsec** [posva/vue-plugin-template#14]
Hi. This is a great template ! But, I'm really lost in webpack config. I need to customize the appearance of my component, and test responsive layouts. How can I do it? Simply `import ../../dist/<component>.css` inside the test spec doesn't work. It says I need a loader. Fine! But how ? Where ? Thanks a lot if you can help.

**Comment by posva** [comment]
Hello, I'm glad you like it.
You need to add a css-loader in the `webpack.config.base.js`

But I really recommend you to keep the CSS in the Vue component `style` or include it with

```vue
<style src='component.css'></style>
```

**Comment by onekiloparsec** [comment]
Thanks for answering quickly. I am sorry, I completely missed the point of my actual question... too much work, probably. 

I wanted to know how to import css inside *tests* specs ! 

In fact, I am testing a navbar fixed on top, and when running tests, it doesn't seem to take the inclyded <style> section at all into account.

**Comment by posva** [comment]
It should appear in the visual tests but I don't know if it is possible to write tests for the actual styles, sorry 🙁

**Comment by onekiloparsec** [comment]
Actually, this is my problem: it doesn't appear in the visual tests.
