### ISSUE TITLE
Yarn or npm install not  working

### ISSUE THREAD

**Issue by creotip** [posva/vue-plugin-template#4]
yarn
`error An unexpected error occurred: "https://registry.yarnpkg.com/eslint-plugin-html/-/eslint-plugin-html-2.0.2.tgz: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
`
npm install
`npm ERR! cb() never called!
`

**Comment by posva** [comment]
Looks like the fix wa released just after you tried: https://github.com/BenoitZugmeyer/eslint-plugin-html/releases 😄 
Try installing it again
