### ISSUE TITLE
How to import public scss.

### ISSUE THREAD

**Issue by seekcx** [posva/vue-plugin-template#7]
I am using this project, write a ui framework, i have some basic scss files, want to use in all cases, what should i do? I tried to import it in index.js, but it did not succeed.

```js
// src/index.js
import './common/scss/base.scss'
```

**Comment by seekcx** [comment]
I imported it in test.vue, seemingly can work, do not know if there is a better way.

**Comment by posva** [comment]
If you're importing sass files only on your js, you can use https://github.com/differui/rollup-plugin-sass
If you're using it in both sides, I recommend you using webpack, it'll be easier. I used webpack for css and rollup for js in this project: https://github.com/posva/vue-mdc in case you want to take a look
